name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.typ"]

  pull_request:
    branches: [main]
    paths: ["**.typ"]

  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  pages: write
  contents: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check:
    runs-on: ubuntu-latest

    outputs:
      has_changes: ${{ steps.commit.outputs.changes_detected }}
      commit_hash: ${{ steps.commit.outputs.commit_hash }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Check last commit dates updates
        run: just chk-lcds-upds

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4

  build:
    needs: check

    if: github.event_name != 'schedule' || needs.check.outputs.has_changes != 'false'

    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.check.outputs.commit_hash }}

      - name: Set up Typst
        uses: yusancky/setup-typst@v2
        with:
          version: latest

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Check locale
        run: |
          locale
          locale -a

      - name: Build CVs
        run: just bld-cvs

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./out/

  deploy:
    needs: build

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy artifact to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
