name: Continuos Delivery

on:
  push:
    branches: [main]
    paths: ["**.typ"]

  pull_request:
    branches: [main]
    paths: ["**.typ"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Set up Typst
        uses: yusancky/setup-typst@v2
        id: setup-typst
        with:
          version: "latest"

      - name: Set up Just
        uses: extractions/setup-just@v1
        with:
          just-version: "1.14"

      - name: Build project
        run: |
          just cv

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact for GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: "./*.pdf"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
