name: Continuos Integration

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  cron:
    runs-on: ubuntu-latest

    outputs:
      call_cd: ${{ steps.commit.outputs.changes_detected }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Just
        uses: extractions/setup-just@v1

      - name: Check last commit dates updates
        run: just chk-lcds-upds

      - name: Commit changes
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4

  cd:
    needs: cron
    uses: ./.github/workflows/cd.yaml
    if: needs.cron.outputs.call_cd == 'true'

    permissions:
      pages: write
      contents: read
      id-token: write

    concurrency:
      group: "pages"
      cancel-in-progress: false
